<?php 

// 	$this->data['head'] = '<script type="text/javascript" src="/res/js/foodle-contacts-api.js"></script>';
// 	$this->data['head'] .= '<script type="text/javascript" src="/res/js/foodle-contacts.js"></script>';


$foodleid = '';

if (isset($_REQUEST['foodleid'])) {
	Data_Foodle::requireValidIdentifier($_REQUEST['foodleid']);
	$foodleid = '"' . $_REQUEST['foodleid'] . '"';
}

$this->data['head'] = '
		
<script type="text/javascript" src="/res/js/foodle-data.js"></script>
<script type="text/javascript" src="/res/js/foodle-groupmanage.js"></script>
<script type="text/javascript">
	$(document).ready(function() {
		Foodle_GroupManage_View(' . $foodleid . ');
	});
</script>
';

$this->includeAtTemplateBase('includes/header.php'); 

$user = $this->data['user'];

?>


<div class="columned">
	<div class="gutter"></div>
	<div class="col4">


		
		<h2><?php echo $this->t('groups'); ?></h2>
				
		<div class="foodle_contactlists" style="margin: 1em 0px">
		</div>

		<form id="foodle_form_add_contactlist" action="/" method="get" style="margin-top: 1em">
			<fieldset>
				<legend><?php echo $this->t('groups_addnew'); ?></legend>
				<input id="foodle_add_contactlist_name" type="text" style="width: 75%" />
				<input type="submit" style="width: 30%" value="<?php echo $this->t('groups_add'); ?>" />
			</fieldset>
		</form>



	</div>
	<div class="col5">




		
		<div class="foodle_contacts">
		</div>
		
		<h2 style="margin-top: 2em"><?php echo $this->t('groups_addcontacts'); ?></h2>
		
			
		<form id="foodle_form_search_contacts" action="/" method="get" style="margin-top: 1em">
			<fieldset>
				<legend><?php echo $this->t('groups_search'); ?></legend>
				<input type="search" id="foodle_contact_search" style="width: 100%" />
			</fieldset>
			
			<p>
				<?php echo $this->t('groups_showcontacts'); ?>
			<select id="foodle_contact_lookuptype" name="foodle_contact_lookuptype">
				<option id="foodle__auto__" value="__auto__"><?php echo $this->t('groups_autogeneratedsuggestions'); ?></option>
				<option id="foodle__search__" value="__search__"><?php echo $this->t('groups_searchretults'); ?></option>
			</select>
			</p>

		</form>

		<div class="foodle_autolist">
		</div>


			
	</div>
	<div class="col6">




			<h2>
				<?php echo $this->t('groups_managing'); ?>
			</h2>
			
			<p><?php echo $this->t('groups_par1'); ?></p>
			
			<p>
				<?php echo $this->t('groups_par2'); ?>
			</p>
			
			<p><?php echo $this->t('groups_cats'); ?></p>
			
			<div><img src="/res/user_red.png" />
				<?php echo $this->t('groups_owner'); ?>
			</div>

			<div><img src="/res/user_suit.png" />
				<?php echo $this->t('groups_admin'); ?>
			</div>
				
			<div><img src="/res/user_grey.png" />
				<?php echo $this->t('groups_member'); ?>
			</div>

	</div><!-- /#col3 -->
	<br style="height: 0px; clear: both">
</div>




			
<?php $this->includeAtTemplateBase('includes/footer.php'); ?>
